# .graphclientrc.yml
sources:
  - name: ButerinCardsGoerli
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/41656/buterincardsgoerli/v0.1.5

documents:
  - ./topminers.graphql